[rabbitmq]
rabbitmq1 ansible_host=103.76.53.131
rabbitmq2 ansible_host=89.169.161.244
# rabbitmq3 ansible_host=192.168.0.12

[rabbitmq:vars]
rabbitmq_user=ekotukov
rabbitmq_password=ekotukov
rabbitmq_erlang_cookie=12345
